name: Mobile-Created Action

on: [push] # Chạy mỗi khi bạn push code lên

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo "Hello World từ điện thoại của tôi!"
        
